version: 1

handlers:
    console:
        class: logging.StreamHandler
        level: WARNING
        formatter: simple
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: detailed
        filename: var/site.log
        mode: a+
        maxBytes: 10485760
        backupCount: 5

root:
    level: NOTSET
    handlers: [console, file]

loggers:
    gevent:
        #level: WARNING
        handlers: [console, file]
        propagate: no
    app:
        #level: WARNING
        handlers: [console, file]

formatters:
    simple:
        format: '%(levelname)-8s %(name)-10s %(message)s'
    detailed:
        format: |-

            ===== %(levelname)s at %(asctime)s =====

            %(message)s
